### ISSUE TITLE
Please consider posting this on the FreeCAD User Showcase forum when ready

### ISSUE THREAD

**Issue by luzpaz** [jmfriedt/harmonic_analyzer_FreeCAD#1]
https://forum.freecadweb.org/viewforum.php?f=24
If you do, please add the full FC version you used and a (short or long) explanation on why/how you made this interesting project, lessons learned etc...
Mote screenshots (and bonus screencasts) are also very welcomed!

**Comment by jmfriedt** [comment]
https://forum.freecadweb.org/viewtopic.php?f=24&t=42040
